// 投手ポジション
export const PITCHER_POSITIONS = [
	{ value: 'SP', label: '先発（SP）' },
	{ value: 'RP', label: '中継ぎ（RP）' },
	{ value: 'CL', label: '抑え（CL）' },
];

// 野手ポジション
export const BATTER_POSITIONS = [
	{ value: 'C', label: 'キャッチャー（C）' },
	{ value: '1B', label: 'ファースト（1B）' },
	{ value: '2B', label: 'セカンド（2B）' },
	{ value: '3B', label: 'サード（3B）' },
	{ value: 'SS', label: 'ショート（SS）' },
	{ value: 'LF', label: 'レフト（LF）' },
	{ value: 'CF', label: 'センター（CF）' },
	{ value: 'RF', label: 'ライト（RF）' },
	{ value: 'DH', label: '指名打者（DH）' },
	{ value: 'UT', label: 'ユーティリティ（UT）' },
];

// 弾道定義
export const TRAJECTORIES = [
	{ value: '1', label: 'グラウンダー' },
	{ value: '2', label: '低弾道' },
	{ value: '3', label: '中弾道' },
	{ value: '4', label: '高弾道' },
	{ value: '5', label: 'パワーヒッター' },
	{ value: '6', label: 'アーチスト' },
	{ value: '7', label: 'ラインドライブ' },
];

// 超特能定義（投手）
export const PITCHER_SUPER_SKILLS = [
	{ value: '1', label: '超ノビ' },
	{ value: '2', label: '超キレ' },
	{ value: '3', label: '超援護' },
	{ value: '4', label: '超奪三振' },
	{ value: '5', label: '超コントロール' },
	{ value: '6', label: '超対ピンチ' },
	{ value: '7', label: '超豪速球' },
	{ value: '8', label: '超重い球' },
	{ value: '9', label: '超存在感' },
	{ value: '10', label: '超打たれ強さ' },
	{ value: '10', label: '超対左打者' },
	{ value: '11', label: '超対右打者' },
	{ value: '12', label: '超奪三振ショー' },
	{ value: '13', label: '超緩急' },
	{ value: '14', label: '超グランドボーラー' },
	{ value: '15', label: '超奥行き' },
];

export const PITCHER_SKILLS = [
	{ value: '1', label: 'ノビ' },
	{ value: '2', label: 'キレ' },
	{ value: '3', label: '援護' },
	{ value: '4', label: '奪三振' },
	{ value: '5', label: 'コントロール' },
	{ value: '6', label: '対ピンチ' },
	{ value: '7', label: '豪速球' },
	{ value: '8', label: '重い球' },
	{ value: '9', label: '存在感' },
	{ value: '10', label: '打たれ強さ' },
	{ value: '10', label: '対左打者' },
	{ value: '11', label: '対右打者' },
	{ value: '12', label: '安定感' },
	{ value: '13', label: '緩急' },
	{ value: '14', label: 'グランドボーラー' },
	{ value: '15', label: '奥行き' },
	{ value: '16', label: '対ランナー' },
	{ value: '17', label: '球持ち' },
	{ value: '18', label: '尻上がり' },
	{ value: '19', label: '対強打者' },
	{ value: '20', label: '闘志' },
	{ value: '21', label: '荒れ球' },
	{ value: '22', label: '白熱' },
	{ value: '23', label: 'クイック' },
	{ value: '24', label: '中日キラー' },
	{ value: '25', label: '要所◯' },
	{ value: '26', label: '選抜' },
	{ value: '27', label: '激闘' },
	{ value: '28', label: '人気' },
	{ value: '29', label: '秀逸' },
	{ value: '30', label: '祝宴' },
	{ value: '31', label: '緩急' },
	{ value: '32', label: '内角◯' },
	{ value: '33', label: '外角◯' },
	{ value: '34', label: '熱気' },
	{ value: '35', label: '楽天キラー' },
	{ value: '36', label: '巨人キラー' },
	{ value: '37', label: 'エースの風格' },
	{ value: '38', label: '兆し' },
	{ value: '39', label: '安全圏' },
	{ value: '40', label: '阪神キラー' },
];

// 超特能定義（野手）
export const BATTER_SUPER_SKILLS = [
	{ value: '1', label: '超アーチスト' },
	{ value: '2', label: '超広角打法' },
	{ value: '3', label: '超アベレージヒッター' },
	{ value: '4', label: '超ハイアベレージヒッター' },
	{ value: '5', label: '超チャンスメーカー' },
	{ value: '6', label: '超チャンス' },
	{ value: '8', label: '超代打の神様' },
	{ value: '9', label: '超プルヒッター' },
	{ value: '10', label: '超パワーヒッター' },
	{ value: '9', label: '超ハイボールヒッター' },
	{ value: '10', label: '超固め打ち' },
	{ value: '10', label: '超おかわり' },
	{ value: '11', label: '超選球眼' },
	{ value: '12', label: '超ラインドライブ' },
	{ value: '13', label: '超流し打ち' },
	{ value: '14', label: '超グランドボーラー' },
	{ value: '15', label: '超奥行き' },
];
