// 投手ポジション
export const PITCHER_POSITIONS = [
	{ value: 'SP', label: '先発（SP）' },
	{ value: 'RP', label: '中継ぎ（RP）' },
	{ value: 'CL', label: '抑え（CL）' },
];

// 野手ポジション
export const BATTER_POSITIONS = [
	{ value: 'C', label: 'キャッチャー（C）' },
	{ value: '1B', label: 'ファースト（1B）' },
	{ value: '2B', label: 'セカンド（2B）' },
	{ value: '3B', label: 'サード（3B）' },
	{ value: 'SS', label: 'ショート（SS）' },
	{ value: 'LF', label: 'レフト（LF）' },
	{ value: 'CF', label: 'センター（CF）' },
	{ value: 'RF', label: 'ライト（RF）' },
	{ value: 'DH', label: '指名打者（DH）' },
	{ value: 'UT', label: 'ユーティリティ（UT）' },
];

// 弾道定義
export const TRAJECTORIES = [
	{ value: '1', label: 'グラウンダー' },
	{ value: '2', label: '低弾道' },
	{ value: '3', label: '中弾道' },
	{ value: '4', label: '高弾道' },
	{ value: '5', label: 'パワーヒッター' },
	{ value: '6', label: 'アーチスト' },
	{ value: '7', label: 'ラインドライブ' },
];

// 超特能定義（投手）
export const PITCHER_SUPER_SKILLS = [
	{ value: 1, label: '超ノビ' },
	{ value: 2, label: '超キレ' },
	{ value: 3, label: '超援護' },
	{ value: 4, label: '超奪三振' },
	{ value: 5, label: '超コントロール' },
	{ value: 6, label: '超対ピンチ' },
	{ value: 7, label: '超豪速球' },
	{ value: 8, label: '超重い球' },
	{ value: 9, label: '超存在感' },
	{ value: 10, label: '超打たれ強さ' },
	{ value: 11, label: '超対左打者' },
	{ value: 12, label: '超対右打者' },
	{ value: 13, label: '超奪三振ショー' },
	{ value: 14, label: '超緩急' },
	{ value: 15, label: '超グランドボーラー' },
	{ value: 16, label: '超奥行き' },
];

export const PITCHER_SKILLS = [
	{ value: 1, label: 'ノビ' },
	{ value: 2, label: 'キレ' },
	{ value: 3, label: '援護' },
	{ value: 4, label: '奪三振' },
	{ value: 5, label: 'コントロール' },
	{ value: 6, label: '対ピンチ' },
	{ value: 7, label: '豪速球' },
	{ value: 8, label: '重い球' },
	{ value: 9, label: '存在感' },
	{ value: 10, label: '打たれ強さ' },
	{ value: 11, label: '対左打者' },
	{ value: 12, label: '対右打者' },
	{ value: 13, label: '安定感' },
	{ value: 14, label: '緩急' },
	{ value: 15, label: 'グランドボーラー' },
	{ value: 16, label: '奥行き' },
	{ value: 17, label: '対ランナー' },
	{ value: 18, label: '球持ち' },
	{ value: 19, label: '尻上がり' },
	{ value: 20, label: '対強打者' },
	{ value: 21, label: '闘志' },
	{ value: 22, label: '荒れ球' },
	{ value: 23, label: '白熱' },
	{ value: 24, label: 'クイック' },
	{ value: 25, label: '中日キラー' },
	{ value: 26, label: '要所◯' },
	{ value: 27, label: '選抜' },
	{ value: 28, label: '激闘' },
	{ value: 29, label: '人気' },
	{ value: 30, label: '秀逸' },
	{ value: 31, label: '祝宴' },
	{ value: 32, label: '内角◯' },
	{ value: 33, label: '外角◯' },
	{ value: 34, label: '熱気' },
	{ value: 35, label: '楽天キラー' },
	{ value: 36, label: '巨人キラー' },
	{ value: 37, label: 'エースの風格' },
	{ value: 38, label: '兆し' },
	{ value: 39, label: '安全圏' },
	{ value: 40, label: '阪神キラー' },
];

// 超特能定義（野手）
export const BATTER_SUPER_SKILLS = [
	{ value: 1, label: '超アーチスト' },
	{ value: 2, label: '超広角打法' },
	{ value: 3, label: '超アベレージヒッター' },
	{ value: 4, label: '超ハイアベレージヒッター' },
	{ value: 5, label: '超チャンスメーカー' },
	{ value: 6, label: '超チャンス' },
	{ value: 7, label: '超代打の神様' },
	{ value: 8, label: '超プルヒッター' },
	{ value: 9, label: '超パワーヒッター' },
	{ value: 10, label: '超ハイボールヒッター' },
	{ value: 11, label: '超固め打ち' },
	{ value: 12, label: '超おかわり' },
	{ value: 13, label: '超選球眼' },
	{ value: 14, label: '超ラインドライブ' },
	{ value: 15, label: '超流し打ち' },
	{ value: 16, label: '超盗塁' },
	{ value: 17, label: '超捕手' },
];

// 特能定義（野手）
export const BATTER_SKILLS = [
	{ value: 1, label: 'アーチスト' },
	{ value: 2, label: '広角打法' },
	{ value: 3, label: 'アベレージヒッター' },
	{ value: 4, label: 'ハイアベレージヒッター' },
	{ value: 5, label: 'チャンスメーカー' },
	{ value: 6, label: 'チャンス' },
	{ value: 7, label: '代打の神様' },
	{ value: 8, label: 'プルヒッター' },
	{ value: 9, label: 'パワーヒッター' },
	{ value: 10, label: 'ハイボールヒッター' },
	{ value: 11, label: '固め打ち' },
	{ value: 12, label: 'おかわり' },
	{ value: 13, label: '選球眼' },
	{ value: 14, label: 'ラインドライブ' },
	{ value: 15, label: '流し打ち' },
	{ value: 16, label: '盗塁' },
	{ value: 17, label: 'エリア51' },
	{ value: 18, label: 'イチロー' },
	{ value: 19, label: '守備職人' },
	{ value: 20, label: '粘り打ち' },
	{ value: 21, label: '内野安打' },
	{ value: 22, label: '初球' },
	{ value: 23, label: 'フルスイング' },
	{ value: 24, label: '熱気' },
	{ value: 25, label: '逆境' },
];

// 投手ロール定義
export const PITCHER_ROLES = [
	{ value: 1, label: '先発1' },
	{ value: 2, label: '先発2' },
	{ value: 3, label: '先発3' },
	{ value: 4, label: '先発4' },
	{ value: 5, label: '先発5' },
	{ value: 6, label: '中継ぎ1' },
	{ value: 7, label: '中継ぎ2' },
	{ value: 8, label: '中継ぎ3' },
	{ value: 9, label: '中継ぎ4' },
	{ value: 10, label: '中継ぎ5' },
	{ value: 11, label: '抑え' },
];
